repos:
  - repo: local
    hooks:
      - id: check
        name: Check code quality
        entry: ./scripts/check.sh
        language: script
      - id: test
        name: Analyze and test code
        entry: ./scripts/test.sh
        language: script